{% set name = "avio" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - "{{ compiler('cxx') }}"  #[win]
    - "{{ compiler('gcc') }}"  #[linux]
    - python
    - cmake
    - ninja
    - ffmpeg  #[win]
    - numpy   #[win]
    - opencv  #[linux]
    - sdl2_ttf

  host:
    - python
    - pip
    - zlib
    - ffmpeg  #[win]
    - numpy   #[win]
    - opencv  #[linux]
    - sdl2_ttf

  run:
    - python
    - zlib
    - ffmpeg  #[win]
    - numpy   #[win]
    - opencv  #[linux]
    - sdl2_ttf

test:
  requires:
    - pytest
  imports:
    - avio
  source_files:
    - tests
  commands:
    - python -m pytest

about:
  summary: A python media processing module
  license_file: LICENSE
  