{% set version = "1.0.0" %}

package:
  name: avio
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - "{{ compiler('cxx') }}"  #[win]
    - "{{ compiler('gcc') }}"  #[unix]
    - python
    - cmake
    - ninja
    - numpy
    - ffmpeg
    - sdl2_ttf

  host:
    - python
    - pip
    - numpy
    - ffmpeg
    - sdl2_ttf

  run:
    - python
    - numpy
    - ffmpeg
    - sdl2_ttf

test:
  requires:
    - pytest
  imports:
    - avio
  source_files:
    - tests
  commands:
    - python -m pytest

about:
  summary: A python media processing module
  license_file: LICENSE
